## This is the result app pod for end users

apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-app-container
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80