## This is the voting app pod for end users

apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app-container
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80